### ISSUE TITLE
Failure to bundle install the gem

### ISSUE THREAD

**Issue by Congrammers** [mkhairi/billplz-api#1]
I am trying to install gem using bundler. I setup the initializers. and I got errors as below.

/home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'billplz-api'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant Billplz::Flexirest
Backtrace for gem load error is:
/home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/billplz-api-0.1.0/lib/billplz/model.rb:2:in `<module:Billplz>'
/home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/billplz-api-0.1.0/lib/billplz/model.rb:1:in `<top (required)>'
/home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/billplz-api-0.1.0/lib/billplz-api.rb:8:in `<top (required)>'
/home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:91:in `require'
/home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:86:in `each'
/home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:86:in `block in require'
/home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:75:in `each'
/home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler/runtime.rb:75:in `require'
/home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.5/lib/bundler.rb:107:in `require'
/home/bantu-hakim/Workspace/Bantu/ProjectAPI/config/application.rb:17:in `<top (required)>'
/home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:156:in `require'
/home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:156:in `require_application_and_environment!'
/home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:77:in `console'
/home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
/home/bantu-hakim/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

**Comment by fathiabdulrahim** [comment]
A new version has been released ,please use the new version. Thank you.

**Comment by Congrammers** [comment]
ty for the fast fix
