### ISSUE TITLE
Bill creation take from environment variable instead of parameters

### ISSUE THREAD

**Issue by Congrammers** [mkhairi/billplz-api#2]
This code below is taken from documentation, it imply that bill will be created based on given collection id:

`bill = Billplz::Bill.create(collection_id: "ajij091j", email: "admin@billplz.com", name:"Admin BillPlz", amount: 200, callback_url: "billplz.com", description: "Shopping Items")`

the bug probably coming from the code below in bills.rb
```
def replace_body(name, request)
      if name == :create
        #add collection id here
        request.post_params = request.post_params.merge(collection_id: "#{ENV['BILLPLZ_COLLECTION_ID']}")
        request.body = request.post_params.to_json
      end
    end
```

**Comment by mkhairi** [comment]
@Congrammers, sorry,  that code should not exist...  fixed 035f468afa6e22275f5df80a82573b0d783e144c . Thanks
