### ISSUE TITLE
Deleting expired bill

### ISSUE THREAD

**Issue by waghih** [mkhairi/billplz-api#5]
Hi,

Not really an actual issue but, is there a way to automatically remove unused bill?
There are two scenario for example:

1. Bill is expired.
2. User close the window during checkout process

**Comment by fathiabdulrahim** [comment]
Hi, 

U need to identify which bill are unused manually and u can use `Delete Bill` endpoint

example : 
`bill = Billplz::Bill.delete(id: "arutnv89")`
